#!/bin/bash
# ********************************************************
#
# Project: nita
#
# Copyright (c) Juniper Networks, Inc., 2024. All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache 2.0 License (the "License"). You may not use this code except in compliance with the License. This code is not an official Juniper product. You can obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.html
#
# SPDX-License-Identifier: Apache-2.0
#
# Third-Party Code: This code may depend on other components under separate copyright notice and license terms. Your use of the source code for those components is subject to the terms and conditions of the respective license as noted in the Third-Party source code file.
#
# ********************************************************

# Priority order is top down

if [ -x "$(command -v kubectl)" ]; then

    CMD="kubectl get namespace nita"

elif [ -x "$(command -v docker)" ]; then

    CMD="echo Unsupported command"

else

  echo 'Error: cannot find required binaries.' >&2
  exit 1

fi

[ ${_CLI_RUNNER_DEBUG} ] && echo ${CMD}>&2

eval "${CMD}"
