# ********************************************************
#
# Project: nita-webapp
#
# Copyright (c) Juniper Networks, Inc., 2021. All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache 2.0 License (the "License"). You may not use this code except in compliance with the License. This code is not an official Juniper product. You can obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.html
#
# SPDX-License-Identifier: Apache-2.0
#
# Third-Party Code: This code may depend on other components under separate copyright notice and license terms. Your use of the source code for those components is subject to the terms and conditions of the respective license as noted in the Third-Party source code file.
#
# ********************************************************
OS_dir: /var/tmp/
OS_package:
OS_version:
autonomous_system: 65200
build_dir: /var/tmp/build
evpn_ibgp:
- group: EVPN_iBGP
  neighbors:
  - name: 10.30.100.3
  - name: 10.30.100.4
final_push: 'False'
firewall_rules:
- from_zone: VRF_10001
  to_zone: VRF_10002
- from_zone: VRF_10002
  to_zone: VRF_10001
- from_zone: VRF_10002
  to_zone: VRF_10003
- from_zone: VRF_10003
  to_zone: VRF_10002
gateway: 100.123.0.1
junos_conf: '{{build_dir}}/{{ inventory_hostname }}/junos.conf'
leaf_type: server
log: '{{build_dir}}/ansible-run.log'
log_dir: '{{build_dir}}/log'
login_message: '***********************************************************************\nThis
  system is restricted to __________, authorized users for legitimate\nbusiness purposes
  only. All activity on the system will be logged and\nis subject to monitoring. Unauthorized
  access, use or modification\nof computers, data therein or data in transit to or
  from the computers\nis a violation of state and federal laws. Unauthorized activity
  will\nbe reported to the law enforcement for investigation and possible\nprosecution.
  __________ reserves the right to investigate, refer for\nprosecution and pursue
  monetary damages in civil actions in the event\nof unauthorized access.\n***********************************************************************\n'
loopback_subnet: 10.30.100.0/24
nameserver: 100.123.0.1
netbox_pass: Juniper!1
netbox_site_name: JCL DC1
netbox_token: 8a099878e119b9e230b20cba3a091a5e9144bd40
netbox_url: https://100.123.35.1
netbox_user: netbox
netconf_passwd: Juniper!1
netconf_port: 22
netconf_user: jcluser
ntpserver: 100.123.0.1
password_hashes:
  netadmin_user: $1$a31gJmWG$h9ohikT1ajySf/tVH.gmv1
  root_user: $1$DbZ1Q3pj$s48cZytjsmSJRUJAf4LdM.
route_filter: 10.30.0.0/16
routing_options:
- destination: 100.123.0.1
  static: 0.0.0.0/0
snmp:
  communities:
  - name: public
  contact: aburston@juniper.net
  location: JCL Labs
tmp_dir: '{{build_dir}}/{{inventory_hostname}}/tmp'
vm_passwd: Juniper!1
vm_user: root
vnis:
- id: 1001
  irb_ips:
  - ip: 10.1.1.1/24
  irb_mac: 02:0a:01:01:01:18
- id: 2001
  irb_ips:
  - ip: 10.2.1.1/24
  irb_mac: 02:0a:02:01:01:18
- id: 3001
  irb_ips:
  - ip: 10.3.1.1/24
  irb_mac: 02:0a:03:01:01:18
wait_time: 800
xml_dir: '{{build_dir}}/{{ inventory_hostname }}/xml'
